[PHP]
post_max_size = 100M
memory_limit=500M
upload_max_filesize = 100M
variables_order = EGPCS
error_log = /var/www/html/logs/php-fpm.log

[opcache]
; Determines if Zend OPCache is enabled
opcache.enable=${PHP_OPCACHE_ENABLE}

; Determines if Zend OPCache is enabled for the CLI version of PHP
opcache.enable_cli=${PHP_OPCACHE_ENABLE}

; The OPcache shared memory storage size.
opcache.memory_consumption=${PHP_OPCACHE_MEMORY_CONSUMPTION}

; The amount of memory for interned strings in Mbytes.
opcache.interned_strings_buffer=${PHP_OPCACHE_INTERNED_STRINGS_BUFFER}

; The maximum number of keys (scripts) in the OPcache hash table.
; Only numbers between 200 and 1000000 are allowed.
opcache.max_accelerated_files=${PHP_OPCACHE_MAX_ACCELERATED_FILES}
